---
service: BotPlay

custom:
  debug: '*'

  services:
    table_name: ${self:service}-accessTokens
  
  nav:
    event_path: event
    install_path: install
    install_redirect: https://slack.com
  
  slack:
    verification_token: "xxx"
    client_scopes: "bot commands"
    client_id: "xxxxxxxxxxxxxxxxxx"
    client_secret: "xxxxxxxxxxxxxxxxxx"

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:DescribeTable
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*